-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('STAFF_USER_BOOTSTRAPPED', 'STAFF_USER_CREATED', 'SELECTION_SETTLED', 'MARKET_SUSPENDED', 'MARKET_UNSUSPENDED', 'COMPETITION_RANKING_SET', 'COMPETITION_RANKING_REMOVED', 'TEAM_COLOR_SET', 'DISPLAY_NAME_OVERRIDE_SET', 'BRAND_IMAGE_SET', 'BRAND_IMAGE_REMOVED', 'COMPETITION_TIER_SET', 'COMPETITION_TIER_REMOVED', 'MARGIN_CONFIG_SET', 'MARGIN_CONFIG_REMOVED', 'MARKETING_SPEND_CREATED', 'MARKETING_SPEND_REMOVED', 'BRAND_IMAGE_LIST_ITEM_ADDED', 'BRAND_IMAGE_LIST_ITEM_REMOVED', 'BRAND_IMAGE_LIST_REORDERED', 'COMPETITION_SUSPENDED', 'COMPETITION_UNSUSPENDED', 'ODDS_OVERRIDE_SET', 'ODDS_OVERRIDE_CLEARED', 'MANUAL_MARKET_CREATED', 'MANUAL_MARKET_REMOVED', 'MANUAL_MARKET_UPDATED', 'ODDS_LADDER_RUNG_ADDED', 'ODDS_LADDER_RUNG_REMOVED', 'ODDS_LADDER_REGENERATED', 'BOOST_SET', 'BOOST_CLEARED', 'ACCA_BOOST_CONFIG_SET', 'STAKE_LIMIT_SET', 'STAKE_LIMIT_REMOVED', 'STAKE_LIMITS_BULK_IMPORTED', 'COMPETITION_QUICKLINK_SET', 'COMPETITION_QUICKLINK_REMOVED', 'PLAYER_SEGMENT_CREATED', 'PLAYER_SEGMENT_REMOVED', 'PLAYER_SEGMENT_MEMBER_ADDED', 'PLAYER_SEGMENT_MEMBER_REMOVED', 'PLAYER_SEGMENT_COLOR_SET', 'MANUAL_MARKET_LIMITS_SET', 'BOOST_LIMITS_SET', 'BOOST_AUTO_DISABLED', 'MANUAL_MARKET_AUTO_DISABLED', 'FREEBET_GRANTED', 'FREEBET_VOIDED', 'ACCA_ROLLBACK_CONFIG_SET', 'INSURANCE_BET_CONFIG_SET', 'BET_AND_GET_CAMPAIGN_CREATED', 'BET_AND_GET_CAMPAIGN_UPDATED', 'BET_AND_GET_CAMPAIGN_REMOVED', 'BET_AND_GET_CAMPAIGN_SCOPES_SET', 'PROMO_CARD_ADDED', 'PROMO_CARD_REMOVED', 'PROMO_CARD_REORDERED');
ALTER TABLE "audit_log_entries" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "public"."AuditAction_old";
COMMIT;

-- AlterTable
ALTER TABLE "bet_and_get_campaigns" DROP COLUMN "bannerData",
DROP COLUMN "bannerMimeType";

-- CreateTable
CREATE TABLE "promo_cards" (
    "id" TEXT NOT NULL,
    "brandId" TEXT NOT NULL,
    "data" BYTEA NOT NULL,
    "mimeType" TEXT NOT NULL,
    "title" TEXT,
    "subtitle" TEXT,
    "sortOrder" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "betAndGetCampaignId" TEXT,

    CONSTRAINT "promo_cards_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "promo_cards_brandId_sortOrder_idx" ON "promo_cards"("brandId", "sortOrder");

-- AddForeignKey
ALTER TABLE "promo_cards" ADD CONSTRAINT "promo_cards_brandId_fkey" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "promo_cards" ADD CONSTRAINT "promo_cards_betAndGetCampaignId_fkey" FOREIGN KEY ("betAndGetCampaignId") REFERENCES "bet_and_get_campaigns"("id") ON DELETE SET NULL ON UPDATE CASCADE;

